# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f551bea036bc7f0f6287a2098238e87a"
name = "DataNorden"
handle = "datanorden"
application_url = "https://parking-publishing-hepatitis-nextel.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "siggaard.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,write_inventory,write_locations,write_products"

[auth]
redirect_urls = [
  "https://parking-publishing-hepatitis-nextel.trycloudflare.com/auth/callback",
  "https://parking-publishing-hepatitis-nextel.trycloudflare.com/auth/shopify/callback",
  "https://parking-publishing-hepatitis-nextel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
