name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
predev = "npx prisma generate"
dev = "npx prisma generate && npx prisma migrate deploy && npm exec remix vite:dev -- --host 0.0.0.0"
